const elements = [
  {
    name: 'Hydrogen',
    name_ja: '水素',
    name_zh: '氫',
    side: '巠',
    number: 1,
    period: 1,
    group: 1,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'H',
  },
  {
    name: 'Helium',
    name_ja: 'ヘリウム',
    name_zh: '氦',
    side: '亥',
    number: 2,
    period: 1,
    group: 18,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'He',
  },
  {
    name: 'Lithium',
    name_ja: 'リチウム',
    name_zh: '鋰',
    side: '里',
    number: 3,
    period: 2,
    group: 1,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Li',
  },
  {
    name: 'Beryllium',
    name_ja: 'ベリリウム',
    name_zh: '鈹',
    side: '皮',
    number: 4,
    period: 2,
    group: 2,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Be',
  },
  {
    name: 'Boron',
    name_ja: 'ホウ素',
    name_zh: '硼',
    side: '朋',
    number: 5,
    period: 2,
    group: 13,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'B',
  },
  {
    name: 'Carbon',
    name_ja: '炭素',
    name_zh: '碳',
    side: '炭',
    number: 6,
    period: 2,
    group: 14,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'C',
  },
  {
    name: 'Nitrogen',
    name_ja: '窒素',
    name_zh: '氮',
    side: '炎',
    number: 7,
    period: 2,
    group: 15,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'N',
  },
  {
    name: 'Oxygen',
    name_ja: '酸素',
    name_zh: '氧',
    side: '羊',
    number: 8,
    period: 2,
    group: 16,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'O',
  },
  {
    name: 'Fluorine',
    name_ja: 'フッ素',
    name_zh: '氟',
    side: '弗',
    number: 9,
    period: 2,
    group: 17,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'F',
  },
  {
    name: 'Neon',
    name_ja: 'ネオン',
    name_zh: '氖',
    side: '乃',
    number: 10,
    period: 2,
    group: 18,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'Ne',
  },
  {
    name: 'Sodium',
    name_ja: 'ナトリウム',
    name_zh: '鈉',
    side: '內',
    number: 11,
    period: 3,
    group: 1,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Na',
  },
  {
    name: 'Magnesium',
    name_ja: 'マグネシウム',
    name_zh: '鎂',
    side: '美',
    number: 12,
    period: 3,
    group: 2,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Mg',
  },
  {
    name: 'Aluminium',
    name_ja: 'アルミニウム',
    name_zh: '鋁',
    side: '呂',
    number: 13,
    period: 3,
    group: 13,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Al',
  },
  {
    name: 'Silicon',
    name_ja: 'ケイ素',
    name_zh: '硅',
    side: '圭',
    number: 14,
    period: 3,
    group: 14,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'Si',
  },
  {
    name: 'Phosphorus',
    name_ja: 'リン',
    name_zh: '磷',
    side: '粦',
    number: 15,
    period: 3,
    group: 15,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'P',
  },
  {
    name: 'Sulfur',
    name_ja: '硫黄',
    name_zh: '硫',
    side: '㐬',
    number: 16,
    period: 3,
    group: 16,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'S',
  },
  {
    name: 'Chlorine',
    name_ja: '塩素',
    name_zh: '氯',
    side: '录',
    number: 17,
    period: 3,
    group: 17,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'Cl',
  },
  {
    name: 'Argon',
    name_ja: 'アルゴン',
    name_zh: '氬',
    side: '亞',
    number: 18,
    period: 3,
    group: 18,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'Ar',
  },
  {
    name: 'Potassium',
    name_ja: 'カリウム',
    name_zh: '鉀',
    side: '甲',
    number: 19,
    period: 4,
    group: 1,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'K',
  },
  {
    name: 'Calcium',
    name_ja: 'カルシウム',
    name_zh: '鈣',
    side: '丐',
    number: 20,
    period: 4,
    group: 2,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ca',
  },
  {
    name: 'Scandium',
    name_ja: 'スカンジウム',
    name_zh: '鈧',
    side: '亢',
    number: 21,
    period: 4,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Sc',
  },
  {
    name: 'Titanium',
    name_ja: 'チタン',
    name_zh: '鈦',
    side: '太',
    number: 22,
    period: 4,
    group: 4,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ti',
  },
  {
    name: 'Vanadium',
    name_ja: 'バナジウム',
    name_zh: '釩',
    side: '凡',
    number: 23,
    period: 4,
    group: 5,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'V',
  },
  {
    name: 'Chromium',
    name_ja: 'クロム',
    name_zh: '鉻',
    side: '各',
    number: 24,
    period: 4,
    group: 6,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Cr',
  },
  {
    name: 'Manganese',
    name_ja: 'マンガン',
    name_zh: '錳',
    side: '孟',
    number: 25,
    period: 4,
    group: 7,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Mn',
  },
  {
    name: 'Iron',
    name_ja: '鉄',
    name_zh: '鐵',
    side: '𢧜',
    number: 26,
    period: 4,
    group: 8,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Fe',
  },
  {
    name: 'Cobalt',
    name_ja: 'コバルト',
    name_zh: '鈷',
    side: '古',
    number: 27,
    period: 4,
    group: 9,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Co',
  },
  {
    name: 'Nickel',
    name_ja: 'ニッケル',
    name_zh: '鎳',
    side: '臬',
    number: 28,
    period: 4,
    group: 10,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ni',
  },
  {
    name: 'Copper',
    name_ja: '銅',
    name_zh: '銅',
    side: '同',
    number: 29,
    period: 4,
    group: 11,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Cu',
  },
  {
    name: 'Zinc',
    name_ja: '亜鉛',
    name_zh: '鋅',
    side: '辛',
    number: 30,
    period: 4,
    group: 12,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Zn',
  },
  {
    name: 'Gallium',
    name_ja: 'ガリウム',
    name_zh: '鎵',
    side: '家',
    number: 31,
    period: 4,
    group: 13,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ga',
  },
  {
    name: 'Germanium',
    name_ja: 'ゲルマニウム',
    name_zh: '鍺',
    side: '者',
    number: 32,
    period: 4,
    group: 14,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ge',
  },
  {
    name: 'Arsenic',
    name_ja: 'ヒ素',
    name_zh: '砷',
    side: '申',
    number: 33,
    period: 4,
    group: 15,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'As',
  },
  {
    name: 'Selenium',
    name_ja: 'セレン',
    name_zh: '硒',
    side: '西',
    number: 34,
    period: 4,
    group: 16,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'Se',
  },
  {
    name: 'Bromine',
    name_ja: '臭素',
    name_zh: '溴',
    side: '臭',
    number: 35,
    period: 4,
    group: 17,
    phase: 'Liquid',
    metal: 'FALSE',
    symbol: 'Br',
  },
  {
    name: 'Krypton',
    name_ja: 'クリプトン',
    name_zh: '氪',
    side: '克',
    number: 36,
    period: 4,
    group: 18,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'Kr',
  },
  {
    name: 'Rubidium',
    name_ja: 'ルビジウム',
    name_zh: '銣',
    side: '如',
    number: 37,
    period: 5,
    group: 1,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Rb',
  },
  {
    name: 'Strontium',
    name_ja: 'ストロンチウム',
    name_zh: '鍶',
    side: '思',
    number: 38,
    period: 5,
    group: 2,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Sr',
  },
  {
    name: 'Yttrium',
    name_ja: 'イットリウム',
    name_zh: '釔',
    side: '乙',
    number: 39,
    period: 5,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Y',
  },
  {
    name: 'Zirconium',
    name_ja: 'ジルコニウム',
    name_zh: '鋯',
    side: '告',
    number: 40,
    period: 5,
    group: 4,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Zr',
  },
  {
    name: 'Niobium',
    name_ja: 'ニオブ',
    name_zh: '鈮',
    side: '尼',
    number: 41,
    period: 5,
    group: 5,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Nb',
  },
  {
    name: 'Molybdenum',
    name_ja: 'モリブデン',
    name_zh: '鉬',
    side: '目',
    number: 42,
    period: 5,
    group: 6,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Mo',
  },
  {
    name: 'Technetium',
    name_ja: 'テクネチウム',
    name_zh: '鍀',
    side: '㝵',
    number: 43,
    period: 5,
    group: 7,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Tc',
  },
  {
    name: 'Ruthenium',
    name_ja: 'ルテニウム',
    name_zh: '釕',
    side: '了',
    number: 44,
    period: 5,
    group: 8,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ru',
  },
  {
    name: 'Rhodium',
    name_ja: 'ロジウム',
    name_zh: '銠',
    side: '老',
    number: 45,
    period: 5,
    group: 9,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Rh',
  },
  {
    name: 'Palladium',
    name_ja: 'パラジウム',
    name_zh: '鈀',
    side: '巴',
    number: 46,
    period: 5,
    group: 10,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pd',
  },
  {
    name: 'Silver',
    name_ja: '銀',
    name_zh: '銀',
    side: '艮',
    number: 47,
    period: 5,
    group: 11,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ag',
  },
  {
    name: 'Cadmium',
    name_ja: 'カドミウム',
    name_zh: '鎘',
    side: '鬲',
    number: 48,
    period: 5,
    group: 12,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Cd',
  },
  {
    name: 'Indium',
    name_ja: 'インジウム',
    name_zh: '銦',
    side: '因',
    number: 49,
    period: 5,
    group: 13,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'In',
  },
  {
    name: 'Tin',
    name_ja: 'スズ',
    name_zh: '錫',
    side: '易',
    number: 50,
    period: 5,
    group: 14,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Sn',
  },
  {
    name: 'Antimony',
    name_ja: 'アンチモン',
    name_zh: '銻',
    side: '弟',
    number: 51,
    period: 5,
    group: 15,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Sb',
  },
  {
    name: 'Tellurium',
    name_ja: 'テルル',
    name_zh: '碲',
    side: '帝',
    number: 52,
    period: 5,
    group: 16,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'Te',
  },
  {
    name: 'Iodine',
    name_ja: 'ヨウ素',
    name_zh: '碘',
    side: '典',
    number: 53,
    period: 5,
    group: 17,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'I',
  },
  {
    name: 'Xenon',
    name_ja: 'キセノン',
    name_zh: '氙',
    side: '山',
    number: 54,
    period: 5,
    group: 18,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'Xe',
  },
  {
    name: 'Cesium',
    name_ja: 'セシウム',
    name_zh: '銫',
    side: '色',
    number: 55,
    period: 6,
    group: 1,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Cs',
  },
  {
    name: 'Barium',
    name_ja: 'バリウム',
    name_zh: '鋇',
    side: '貝',
    number: 56,
    period: 6,
    group: 2,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ba',
  },
  {
    name: 'Lanthanum',
    name_ja: 'ランタン',
    name_zh: '鑭',
    side: '闌',
    number: 57,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'La',
  },
  {
    name: 'Cerium',
    name_ja: 'セリウム',
    name_zh: '鈰',
    side: '市',
    number: 58,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ce',
  },
  {
    name: 'Praseodymium',
    name_ja: 'プラセオジム',
    name_zh: '鐠',
    side: '普',
    number: 59,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pr',
  },
  {
    name: 'Neodymium',
    name_ja: 'ネオジム',
    name_zh: '釹',
    side: '女',
    number: 60,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Nd',
  },
  {
    name: 'Promethium',
    name_ja: 'プロメチウム',
    name_zh: '鉕',
    side: '叵',
    number: 61,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pm',
  },
  {
    name: 'Samarium',
    name_ja: 'サマリウム',
    name_zh: '釤',
    side: '彡',
    number: 62,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Sm',
  },
  {
    name: 'Europium',
    name_ja: 'ユウロピウム',
    name_zh: '銪',
    side: '有',
    number: 63,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Eu',
  },
  {
    name: 'Gadolinium',
    name_ja: 'ガドリニウム',
    name_zh: '釓',
    side: '乚',
    number: 64,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Gd',
  },
  {
    name: 'Terbium',
    name_ja: 'テルビウム',
    name_zh: '鋱',
    side: '忒',
    number: 65,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Tb',
  },
  {
    name: 'Dysprosium',
    name_ja: 'ジスプロシウム',
    name_zh: '鏑',
    side: '啇',
    number: 66,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Dy',
  },
  {
    name: 'Holmium',
    name_ja: 'ホルミウム',
    name_zh: '鈥',
    side: '火',
    number: 67,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ho',
  },
  {
    name: 'Erbium',
    name_ja: 'エルビウム',
    name_zh: '鉺',
    side: '耳',
    number: 68,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Er',
  },
  {
    name: 'Thulium',
    name_ja: 'ツリウム',
    name_zh: '銩',
    side: '丢',
    number: 69,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Tm',
  },
  {
    name: 'Ytterbium',
    name_ja: 'イッテルビウム',
    name_zh: '鐿',
    side: '意',
    number: 70,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Yb',
  },
  {
    name: 'Lutetium',
    name_ja: 'ルテチウム',
    name_zh: '鑥',
    side: '魯',
    number: 71,
    period: 6,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Lu',
  },
  {
    name: 'Hafnium',
    name_ja: 'ハフニウム',
    name_zh: '鉿',
    side: '合',
    number: 72,
    period: 6,
    group: 4,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Hf',
  },
  {
    name: 'Tantalum',
    name_ja: 'タンタル',
    name_zh: '鉭',
    side: '旦',
    number: 73,
    period: 6,
    group: 5,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ta',
  },
  {
    name: 'Tungsten',
    name_ja: 'タングステン',
    name_zh: '鎢',
    side: '烏',
    number: 74,
    period: 6,
    group: 6,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'W',
  },
  {
    name: 'Rhenium',
    name_ja: 'レニウム',
    name_zh: '錸',
    side: '來',
    number: 75,
    period: 6,
    group: 7,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Re',
  },
  {
    name: 'Osmium',
    name_ja: 'オスミウム',
    name_zh: '鋨',
    side: '我',
    number: 76,
    period: 6,
    group: 8,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Os',
  },
  {
    name: 'Iridium',
    name_ja: 'イリジウム',
    name_zh: '銥',
    side: '衣',
    number: 77,
    period: 6,
    group: 9,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ir',
  },
  {
    name: 'Platinum',
    name_ja: '白金',
    name_zh: '鉑',
    side: '白',
    number: 78,
    period: 6,
    group: 10,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pt',
  },
  {
    name: 'Gold',
    name_ja: '金',
    name_zh: '金',
    side: '',
    number: 79,
    period: 6,
    group: 11,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Au',
  },
  {
    name: 'Mercury',
    name_ja: '水銀',
    name_zh: '汞',
    side: '工',
    number: 80,
    period: 6,
    group: 12,
    phase: 'Liquid',
    metal: 'FALSE',
    symbol: 'Hg',
  },
  {
    name: 'Thallium',
    name_ja: 'タリウム',
    name_zh: '鉈',
    side: '它',
    number: 81,
    period: 6,
    group: 13,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Tl',
  },
  {
    name: 'Lead',
    name_ja: '鉛',
    name_zh: '鉛',
    side: '㕣',
    number: 82,
    period: 6,
    group: 14,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pb',
  },
  {
    name: 'Bismuth',
    name_ja: 'ビスマス',
    name_zh: '鉍',
    side: '必',
    number: 83,
    period: 6,
    group: 15,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Bi',
  },
  {
    name: 'Polonium',
    name_ja: 'ポロニウム',
    name_zh: '釙',
    side: '卜',
    number: 84,
    period: 6,
    group: 16,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Po',
  },
  {
    name: 'Astatine',
    name_ja: 'アスタチン',
    name_zh: '砹',
    side: '艾',
    number: 85,
    period: 6,
    group: 17,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'At',
  },
  {
    name: 'Radon',
    name_ja: 'ラドン',
    name_zh: '氡',
    side: '冬',
    number: 86,
    period: 6,
    group: 18,
    phase: 'Gas',
    metal: 'FALSE',
    symbol: 'Rn',
  },
  {
    name: 'Francium',
    name_ja: 'フランシウム',
    name_zh: '鈁',
    side: '方',
    number: 87,
    period: 7,
    group: 1,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Fr',
  },
  {
    name: 'Radium',
    name_ja: 'ラジウム',
    name_zh: '鐳',
    side: '雷',
    number: 88,
    period: 7,
    group: 2,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ra',
  },
  {
    name: 'Actinium',
    name_ja: 'アクチニウム',
    name_zh: '錒',
    side: '阿',
    number: 89,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ac',
  },
  {
    name: 'Thorium',
    name_ja: 'トリウム',
    name_zh: '釷',
    side: '土',
    number: 90,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Th',
  },
  {
    name: 'Protactinium',
    name_ja: 'プロトアクチニウム',
    name_zh: '鏷',
    side: '菐',
    number: 91,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pa',
  },
  {
    name: 'Uranium',
    name_ja: 'ウラン',
    name_zh: '鈾',
    side: '由',
    number: 92,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'U',
  },
  {
    name: 'Neptunium',
    name_ja: 'ネプツニウム',
    name_zh: '鎿',
    side: '拿',
    number: 93,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Np',
  },
  {
    name: 'Plutonium',
    name_ja: 'プルトニウム',
    name_zh: '鈈',
    side: '不',
    number: 94,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Pu',
  },
  {
    name: 'Americium',
    name_ja: 'アメリシウム',
    name_zh: '鎇',
    side: '眉',
    number: 95,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Am',
  },
  {
    name: 'Curium',
    name_ja: 'キュリウム',
    name_zh: '鋦',
    side: '局',
    number: 96,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Cm',
  },
  {
    name: 'Berkelium',
    name_ja: 'バークリウム',
    name_zh: '錇',
    side: '咅',
    number: 97,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Bk',
  },
  {
    name: 'Californium',
    name_ja: 'カリホルニウム',
    name_zh: '鐦',
    side: '開',
    number: 98,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Cf',
  },
  {
    name: 'Einsteinium',
    name_ja: 'アインスタイニウム',
    name_zh: '鎄',
    side: '哀',
    number: 99,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Es',
  },
  {
    name: 'Fermium',
    name_ja: 'フェルミウム',
    name_zh: '鐨',
    side: '費',
    number: 100,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Fm',
  },
  {
    name: 'Mendelevium',
    name_ja: 'メンデレビウム',
    name_zh: '鍆',
    side: '門',
    number: 101,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Md',
  },
  {
    name: 'Nobelium',
    name_ja: 'ノーベリウム',
    name_zh: '鍩',
    side: '若',
    number: 102,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'No',
  },
  {
    name: 'Lawrencium',
    name_ja: 'ローレンシウム',
    name_zh: '鐒',
    side: '勞',
    number: 103,
    period: 7,
    group: 3,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Lr',
  },
  {
    name: 'Rutherfordium',
    name_ja: 'ラザホージウム',
    name_zh: '鑪',
    side: '盧',
    number: 104,
    period: 7,
    group: 4,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Rf',
  },
  {
    name: 'Dubnium',
    name_ja: 'ドブニウム',
    name_zh: '𨧀',
    side: '杜',
    number: 105,
    period: 7,
    group: 5,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Db',
  },
  {
    name: 'Seaborgium',
    name_ja: 'シーボーギウム',
    name_zh: '𨭎',
    side: '喜',
    number: 106,
    period: 7,
    group: 6,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Sg',
  },
  {
    name: 'Bohrium',
    name_ja: 'ボーリウム',
    name_zh: '𨨏',
    side: '波',
    number: 107,
    period: 7,
    group: 7,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Bh',
  },
  {
    name: 'Hassium',
    name_ja: 'ハッシウム',
    name_zh: '𨭆',
    side: '黑',
    number: 108,
    period: 7,
    group: 8,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Hs',
  },
  {
    name: 'Meitnerium',
    name_ja: 'マイトネリウム',
    name_zh: '䥑',
    side: '麥',
    number: 109,
    period: 7,
    group: 9,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Mt',
  },
  {
    name: 'Darmstadtium',
    name_ja: 'ダームスタチウム',
    name_zh: '鐽',
    side: '達',
    number: 110,
    period: 7,
    group: 10,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Ds',
  },
  {
    name: 'Roentgenium',
    name_ja: 'レントゲニウム',
    name_zh: '錀',
    side: '侖',
    number: 111,
    period: 7,
    group: 11,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Rg',
  },
  {
    name: 'Copernicium',
    name_ja: 'コペルニシウム',
    name_zh: '鎶',
    side: '哥',
    number: 112,
    period: 7,
    group: 12,
    phase: 'Liquid',
    metal: 'TRUE',
    symbol: 'Cn',
  },
  {
    name: 'Nihonium',
    name_ja: 'ニホニウム',
    name_zh: '鉨',
    side: '尔',
    number: 113,
    period: 7,
    group: 13,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Nh',
  },
  {
    name: 'Flerovium',
    name_ja: 'フレロビウム',
    name_zh: '鈇',
    side: '夫',
    number: 114,
    period: 7,
    group: 14,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Fl',
  },
  {
    name: 'Moscovium',
    name_ja: 'モスコビウム',
    name_zh: '鏌',
    side: '莫',
    number: 115,
    period: 7,
    group: 15,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Mc',
  },
  {
    name: 'Livermorium',
    name_ja: 'リバモリウム',
    name_zh: '鉝',
    side: '立',
    number: 116,
    period: 7,
    group: 16,
    phase: 'Solid',
    metal: 'TRUE',
    symbol: 'Lv',
  },
  {
    name: 'Tennessine',
    name_ja: 'テネシン',
    name_zh: '鿬',
    side: '田',
    number: 117,
    period: 7,
    group: 17,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'Ts',
  },
  {
    name: 'Oganesson',
    name_ja: 'オガネソン',
    name_zh: '鿫',
    side: '奥',
    number: 118,
    period: 7,
    group: 18,
    phase: 'Solid',
    metal: 'FALSE',
    symbol: 'Og\n',
  },
];
export const quizData = {
  title: '元素',
  quizzes: [
    {
      id: 1,
      phase: elements[5].phase,
      side: elements[5].side,
      options: [
        { text: elements[5].name_ja, answer: true },
        { text: elements[9].name_ja, answer: false },
        { text: elements[13].name_ja, answer: false },
        { text: elements[52].name_ja, answer: false },
      ],
    },
    {
      id: 2,
      phase: elements[77].phase,
      side: elements[77].side,
      options: [
        { text: elements[15].name_ja, answer: false },
        { text: elements[77].name_ja, answer: true },
        { text: elements[29].name_ja, answer: false },
        { text: elements[79].name_ja, answer: false },
      ],
    },
    {
      id: 3,
      phase: elements[16].phase,
      side: elements[16].side,
      options: [
        { text: elements[0].name_ja, answer: false },
        { text: elements[6].name_ja, answer: false },
        { text: elements[7].name_ja, answer: false },
        { text: elements[16].name_ja, answer: true },
      ],
    },
    {
      id: 4,
      phase: elements[10].phase,
      side: elements[10].side,
      options: [
        { text: elements[10].name_ja, answer: true },
        { text: elements[11].name_ja, answer: false },
        { text: elements[17].name_ja, answer: false },
        { text: elements[18].name_ja, answer: false },
      ],
    },
    {
      id: 5,
      phase: elements[33].phase,
      side: elements[33].side,
      options: [
        { text: elements[33].name_ja, answer: true },
        { text: elements[53].name_ja, answer: false },
        { text: elements[57].name_ja, answer: false },
        { text: elements[54].name_ja, answer: false },
      ],
    },
    {
      id: 6,
      phase: elements[30].phase,
      side: elements[30].side,
      options: [
        { text: elements[30].name_ja, answer: true },
        { text: elements[63].name_ja, answer: false },
        { text: elements[47].name_ja, answer: false },
        { text: elements[31].name_ja, answer: false },
      ],
    },
    {
      id: 7,
      phase: elements[60].phase,
      side: elements[60].side,
      options: [
        { text: elements[58].name_ja, answer: false },
        { text: elements[60].name_ja, answer: true },
        { text: elements[90].name_ja, answer: false },
        { text: elements[93].name_ja, answer: false },
      ],
    },
    {
      id: 8,
      phase: elements[75].phase,
      side: elements[75].side,
      options: [
        { text: elements[22].name_ja, answer: false },
        { text: elements[73].name_ja, answer: false },
        { text: elements[75].name_ja, answer: true },
        { text: elements[87].name_ja, answer: false },
      ],
    },
    {
      id: 9,
      phase: elements[64].phase,
      side: elements[64].side,
      options: [
        { text: elements[38].name_ja, answer: false },
        { text: elements[69].name_ja, answer: false },
        { text: elements[67].name_ja, answer: false },
        { text: elements[64].name_ja, answer: true },
      ],
    },
    {
      id: 10,
      phase: elements[107].phase,
      side: elements[107].side,
      options: [
        { text: elements[107].name_ja, answer: true },
        { text: elements[113].name_ja, answer: false },
        { text: elements[99].name_ja, answer: false },
        { text: elements[70].name_ja, answer: false },
      ],
    },
  ],
};
